<?php

/********************************************************* {COPYRIGHT-TOP} ***
 * Licensed Materials - Property of IBM
 * 5725-L30, 5725-Z22
 *
 * (C) Copyright IBM Corporation 2018, 2025
 *
 * All Rights Reserved.
 * US Government Users Restricted Rights - Use, duplication or disclosure
 * restricted by GSA ADP Schedule Contract with IBM Corp.
 ********************************************************** {COPYRIGHT-END} **/

/**
 * @file
 * Provides user management integration with APIC.
 */

use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_menu().
 *
 * @param $variables
 */
function auth_apic_preprocess_menu(&$variables) {
  if (isset($variables['menu_name']) && $variables['menu_name'] === 'account' && array_key_exists('change_pwd_page.change_password', $variables['items'])) {
    $currentUser = \Drupal::currentUser();
    if (!$currentUser->isAnonymous() && $currentUser->id() !== 1) {
      $currentUser = User::load($currentUser->id());
      $registryUrl = $currentUser->get('registry_url')->value;
      if ($registryUrl !== NULL && $registryUrl !== '/admin') {
        $registry = \Drupal::service('ibm_apim.user_registry')->get($registryUrl);
        if ($registry !== NULL) {
          $ro = !$registry->isUserManaged();
          if ($ro === TRUE) {
            unset($variables['items']['change_pwd_page.change_password']);
          }
        }
      }
    }
  }
}

/**
 * Need to use our custom content forms for users
 *
 * @param $variables
 * @param $hook
 * @param $info
 */
function auth_apic_theme($existing, $type, $theme, $path) {
  $definitions = [];

  $template_map = [
    'user_login_form' => 'form--user-login-form',
    'user_register_form' => 'form--user-register-form',
    'user_pass' => 'form--user-pass-form',
    'user_pass_reset' => 'form--user-pass-form',
    'apic_change_pwd_form' => 'form--change-pwd-form',
    'apic_resetpw' => 'form--apic-resetpw',
  ];

  $theme_name = \Drupal::theme()->getActiveTheme()->getName();
  $theme_path = \Drupal::service('extension.list.theme')->getPath($theme_name);
  $module_path = \Drupal::service('extension.list.module')->getPath('auth_apic');

  foreach ($template_map as $form_id => $template_file) {
    $template_path = '';
    if (file_exists($theme_path . '/templates/form/' . $template_file . '.html.twig')) {
      $template_path = $theme_path . '/templates/form';
    }
    elseif (file_exists($theme_path . '/templates/' . $template_file . '.html.twig')) {
      $template_path = $theme_path . '/templates';
    }
    else {
      $template_path = $module_path . '/templates';
    }

    $definitions[$form_id] = [
      'render element' => 'form',
      'template' => $template_file,
      'path' => $template_path,
    ];
  }

  return $definitions;
}